### ISSUE TITLE
考不考虑支持rollup？浏览器环境下需要bundle

### ISSUE THREAD

**Issue by hardfist** [jaywcjlove/tsbb#2]

**Comment by jaywcjlove** [comment]
@hardfist 未来会考虑

**Comment by jaywcjlove** [comment]
@hardfist 目前使用 babel 实现的比较不好

https://github.com/jaywcjlove/tsbb/blob/01b4ff62f1b3333cf2e30ea028711d51c922ffbf/example/react-component/package.json#L52-L71

**Comment by jaywcjlove** [comment]
#120
