### ISSUE TITLE
The test files are not type checked

### ISSUE THREAD

**Issue by kumar303** [jaywcjlove/tsbb#95]
I noticed a few issues when creating a `Basic` app:

- The `tsconfig.json` file excludes test files. This is good for the build but it means there is no type checking of the test code by default. This could be fixed by creating two `tsconfig` files: one for building and one for development. The development one would need `noEmit: true`.
- The `@types/jest` dev dependency is missing. This adds types for `jest` globals like `describe` and `it`.

**Comment by jaywcjlove** [comment]
@kumar303 Welcome to submit PR, THX!

**Comment by kumar303** [comment]
I'm currently not running `tsbb` in production. I was just testing it out against the others listed on the [bootstrapping page](https://www.typescriptlang.org/docs/bootstrap) (it's a good contender!). I think the config splitting will be where the most work is, just to test the bundle and get it configured right. If I ever put a `tsbb` app into production, I may be able to work on a PR for it.

**Comment by kumar303** [comment]
If anyone else wants inspiration for a PR, I had rolled my own previously using [this config](https://github.com/kumar303/skeleton-kit/blob/df682cd62cd860859b8a53a6fcc10075b70f5c5f/tsconfig.json) for development then building a production package without tests [via this config](https://github.com/kumar303/skeleton-kit/blob/df682cd62cd860859b8a53a6fcc10075b70f5c5f/tsconfig-esm.json).
